### PR TITLE
also fix incomplete rename of 'setuppingpong' to 'setup'

### PR DESCRIPTION
**Pull request by boegel**

### CODE REVIEW

**Comment by boegel** [comment]
@stdweird: with this also in place, I obtain a *.h5 file generated by `mympingpong` (single-node, 2 cores)

I'm still running into problems with `mympingponganalysis` however, but that's probably an issue with Tkinter in the Python module built with EB (see below).

So, this should be safe to merge (although I'm not 100% sure yet whether `mympingponganalysis` works as expected.

```
$ mympingponganalysis -f PPnode2581.golett.os-002-msg0001024B-nr00100-it00100-20151029-151602.h5
Traceback (most recent call last):
  File "/user/scratch/gent/vsc400/vsc40023/easybuild_REGTEST/SL6/sandybridge/software/mympingpong/0.6.1-intel-2015b-Python-2.7.10/bin/mympingponganalysis", line 4, in <module>
    __import__('pkg_resources').run_script('mympingpong==0.6.1', 'mympingponganalysis')
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 729, in run_script
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 1642, in run_script
  File "/user/scratchdelcatty/gent/gvo000/gvo00002/vsc40023/easybuild_REGTEST/SL6/sandybridge/software/mympingpong/0.6.1-intel-2015b-Python-2.7.10/lib/python2.7/site-packages/mympingpong-0.6.1-py2.7.egg/EGG-INFO/scripts/mympingponganalysis", line 316, in <module>
    ppa.plot(go.options.colormap, go.options.input, go.options.show, go.options.save, lscale, lmask)
  File "/user/scratchdelcatty/gent/gvo000/gvo00002/vsc40023/easybuild_REGTEST/SL6/sandybridge/software/mympingpong/0.6.1-intel-2015b-Python-2.7.10/lib/python2.7/site-packages/mympingpong-0.6.1-py2.7.egg/EGG-INFO/scripts/mympingponganalysis", line 260, in plot
    fig1 = plt.figure(figsize=(32, 18), dpi=60)
  File "/user/scratchdelcatty/gent/gvo000/gvo00002/vsc40023/easybuild_REGTEST/SL6/sandybridge/software/matplotlib/1.4.3-intel-2015b-Python-2.7.10/lib/python2.7/site-packages/matplotlib-1.4.3-py2.7-linux-x86_64.egg/matplotlib/pyplot.py", line 435, in figure
    **kwargs)
  File "/user/scratchdelcatty/gent/gvo000/gvo00002/vsc40023/easybuild_REGTEST/SL6/sandybridge/software/matplotlib/1.4.3-intel-2015b-Python-2.7.10/lib/python2.7/site-packages/matplotlib-1.4.3-py2.7-linux-x86_64.egg/matplotlib/backends/backend_tkagg.py", line 81, in new_figure_manager
    return new_figure_manager_given_figure(num, figure)
  File "/user/scratchdelcatty/gent/gvo000/gvo00002/vsc40023/easybuild_REGTEST/SL6/sandybridge/software/matplotlib/1.4.3-intel-2015b-Python-2.7.10/lib/python2.7/site-packages/matplotlib-1.4.3-py2.7-linux-x86_64.egg/matplotlib/backends/backend_tkagg.py", line 89, in new_figure_manager_given_figure
    window = Tk.Tk()
  File "/user/scratch/gent/vsc400/vsc40023/easybuild_REGTEST/SL6/sandybridge/software/Python/2.7.10-intel-2015b/lib/python2.7/lib-tk/Tkinter.py", line 1816, in __init__
    self._loadtk()
  File "/user/scratch/gent/vsc400/vsc40023/easybuild_REGTEST/SL6/sandybridge/software/Python/2.7.10-intel-2015b/lib/python2.7/lib-tk/Tkinter.py", line 1832, in _loadtk
    % (_tkinter.TK_VERSION, tk_version)
RuntimeError: tk.h version (8.6) doesn't match libtk.a version (8.5)
```

**Comment by stdweird** [comment]
where is this tested?
where could it get a different header and static lib from?

**Comment by boegel** [comment]
@stdweird: working on a fix, thePython build procedure blatently ignores the Tcl/Tk dirs in `$CPATH` and `$LIBRARY_PATH`, so the Python easyblock should use `--with-tcltk-libs`

**Comment by boegel** [comment]
@stdweird: tracking the Tkinter issue in https://github.com/hpcugent/easybuild-easyblocks/issues/728

**Pull request merged**
