### PR TITLE
Fix tests for python 2.6

### PR DESCRIPTION
**Pull request by wpoely86**
matplotlib dropped support for python 2.6 in version 2.0.0.

### CODE REVIEW

**Comment by boegel** [comment]
@wpoely86 `s/matplotlib/mpi4py/` (also in the description)

**Comment by wpoely86** [comment]
@boegel no, it's matplotlib :wink:

**Comment by wpoely86** [comment]
retest this please

**Comment by wpoely86** [comment]
retest this please

**Pull request merged**
