### PR TITLE
fix broken call to non-existing runpingpong method of MyPingPong class instance

### PR DESCRIPTION
**Pull request by boegel**
Not having _any_ unit tests is biting us in the ass here. Hard.

### CODE REVIEW

**Comment by boegel** [comment]
@stdweird: please review/merge

**Comment by stdweird** [comment]
@boegel thx!

**Comment by JensTimmerman** [comment]
this change needs unit tests!

**Comment by boegel** [comment]
@JensTimmerman: patches welcome, I was trying to get this to work before I left for a while, I felt fixing the bug was more important that starting a test suite from scratch (you can't blame me for not having tests here yet)

**Pull request merged**
