### PR TITLE
Move nose and mock to test_require

### PR DESCRIPTION
**Pull request by wpoely86**
@JensTimmerman

### CODE REVIEW

**Comment by boegel** [comment]
Jenkins: test this please

**Comment by JensTimmerman** [comment]
jenkins test this please with the updated headers in master

**Comment by boegel** [comment]
@JensTimmerman what magic trick did you pull here?

**Comment by JensTimmerman** [comment]
I fixed the errors in a seperate PR https://github.com/hpcugent/mympingpong/pull/15

**Pull request merged**
